### ISSUE TITLE
Create hyprland environment

### ISSUE THREAD

**Issue by turtton** [turtton/dotnix#1]
# TODO
- [x] Install hyprland
- [x] B U Y  R A D E O N  G P U  https://kameuo.turtton.net/notes/a8ubgoqelkxvot2e
- [x] Configure shortcuts
  - [x] Add pin windiw
- ~~Create color schema(Jolly like theme)~~
- [x] Add status bar(eww+hyprbar)
  - [x] Add CVE counter (using vulnix)
  - [x] Add speaker selector
  - [x] Add System tray
  - [x] ~~Add application volume controller~~ use pavucontrol
  - [x] ~~Fix datetime widget~~
- [x] Add launcher(rofi-wayland)
- [x]  ~~Migrate KDE themes for~~ ~~Kvantum and qtct not work for my env~~  Hyprland no have related env value, so I fixed it
  - [x] ~~Dolphin(FileManager)~~ ~~Try Thunar(theme not applied?)~~ ~~Finally, I tried nautilus~~ Dolphin(qt5) works!!!
  - [x] ~~Gwenview(Image viewer and editor)~~ ~~swappy + eog(GNOME Image viewer)~~ Gwenview(qt5) works!!!
  - [x] ~~Spectacle(Screenshot capture)~~ grimblast + swappy + zenity
- [x] ~~Create wallaperengine compatible software for hyprland~~ swww looks so good
- [x] Add good power? login? menu [image](https://private-user-images.githubusercontent.com/85994908/351939013-364f3e9c-a903-4b93-96b5-445027df1c74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NzY1NjUsIm5iZiI6MTczMDk3NjI2NSwicGF0aCI6Ii84NTk5NDkwOC8zNTE5MzkwMTMtMzY0ZjNlOWMtYTkwMy00YjkzLTk2YjUtNDQ1MDI3ZGYxYzc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDEwNDQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2Mzg0YWM4OWE3MmQ4OWJlZmQ3YmVkYTE4OWUzMjhmMzM3ZDhkYmFjYTY2ZGM3YzgwZTk1OTc3ZjIzYzAwY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NKAvagkY0xNbBQDgxn04Y8kcF68GVMp9UbY_VN-dKZ8)
- [x] ~~set neovim as default editor~~ Already configured but not work...
- [x] Add ColorDialog alternative -> gcolor3
- [x] fix SKK
- [x] Fix IME issue on autostarted discord
- [x] ~~Fix vivaldi flickering on search bar~~ Radeon solved this
- [x] Fix keybase not started automatically
- [x] Fix discord defaut workspace
- [x] Fix secondary monitor position
- [x] Fix 1password failed to store two factor token
- [x] Add clipboard history viewer
- [x] ~~Set xdg-desktop-portal-hyprland as default~~ Aready configured
- [x] Set dolphin filemanager as default
- [x] ~~Add graphical NetworkManager connection manager(I want to switch VPN state on GUI)~~ nmcli is good
